# Generated by Django 4.0.3 on 2022-05-25 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0003_alter_company_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='job_offers.company'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(choices=[('contract_of_employment', 'Umowa o pracę'), ('contract_of_mandate', 'Umowa zlecenie'), ('contract_of_commission', 'Umowa o dzieło'), ('business_to_business', 'B2B'), ('other', 'Inne')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='work_mode',
            field=models.CharField(choices=[('stationary', 'Stacjonarny'), ('remote', 'Zdalny'), ('hybrid', 'Hybrydowy')], default='stationary', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='work_time',
            field=models.CharField(choices=[('full', 'Pełny etat'), ('one_second', 'Pół etatu'), ('three_fourth', '3/4 etatu'), ('one_fourth', '1/4 etatu'), ('other', 'Inne')], default='full', max_length=100),
        ),
    ]
